blogio_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_blog_app.urls')),
]

my_blog_app/urls.py
from django.urls import path

from . import views

app_name = 'my_blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic_info, name='topic_info'),
    path('topics/new_topic/', views.new_topic, name='new_topic'),
    path('new_topic_info/<int:topic_id>/', views.new_topic_info, name='new_topic_info'),
]

my_blog_app/models.py
from django.db import models


class Topic(models.Model):
    """Topic model."""
    name = models.CharField(max_length=250)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"


class TopicInfo(models.Model):
    """Information about some topic"""
    topic = models.ForeignKey(Topic, models.CASCADE)
    name = models.CharField(max_length=250)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} {self.text[:30]}"

my_blog_app/forms.py
from django import forms

from .models import Topic, TopicInfo


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['name']


class TopicInfoForm(forms.ModelForm):
    class Meta:
        model = TopicInfo
        fields = ['name', 'text']

my_blog_app/views.py
from django.shortcuts import render, redirect

from .models import Topic
from .forms import TopicForm, TopicInfoForm


def home(request):
    """Home page!"""
    return render(request, 'my_blog_app/home.html')


def topics(request):
    """Show all topics"""
    all_topics = Topic.objects.order_by('date_created')
    context = {'all_topics': all_topics, 'title': 'List of topics!'}
    return render(request, 'my_blog_app/topics.html', context)


def topic_info(request, topic_id):
    """Show info about particular topic!"""
    topic = Topic.objects.get(id=topic_id)
    topic_infos = topic.topicinfo_set.order_by('-date_added')
    context = {'topic': topic, 'topic_infos': topic_infos, 'title': 'Topic infos'}
    return render(request, 'my_blog_app/topic_info.html', context)


def new_topic(request):
    """Create a new topic."""
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('my_blog:topics')
    context = {'form': form, 'title': 'Create new topic.'}
    return render(request, 'my_blog_app/new_topic.html', context)


def new_topic_info(request, topic_id):
    """Create new topic info according to the particular topic."""
    # get single topic for topic id
    topic = Topic.objects.get(id=topic_id)
    # create empty form if method != POST
    if request.method != 'POST':
        form = TopicInfoForm()
    else:
        form = TopicInfoForm(request.POST)
        if form.is_valid():
            new_single_topic_ingo = form.save(commit=False)
            new_single_topic_ingo.topic = topic
            new_single_topic_ingo.save()
            return redirect('my_blog:topic_info', id=topic.id)
    context = {'form': form, 'title': 'Create new Topic Info!', 'topic': topic}
    return render(request, 'my_blog_app/new_topic_info.html', context)

my_blog_app/templates/my_blog_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>My blog!</title>
    {% endif %}
</head>
<body>

    {% block content %}  {% endblock content %}

</body>
</html>

my_blog_app/templates/my_blog_app/home.html
{% extends 'my_blog_app/base.html' %}

{% block content %}
    <h1>Hello, you are on my home page! This page will consist infotmation about topics and their content.</h1>

    <p><a href="{% url 'my_blog:topics' %}">All topics.</a></p>
{% endblock content %}

my_blog_app/templates/my_blog_app/new_topic.html
{% extends 'my_blog_app/base.html' %}

{% block content %}

    <h1>Create new Topic</h1>

<form action="{% url 'my_blog:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add new topic.</button>
</form>

{% endblock content %}

my_blog_app/templates/my_blog_app/new_topic_info.html
{% extends 'my_blog_app/base.html' %}

{% block content %}

    <h1>Create new Topic Info for topic {{ topic.name }}</h1>

<form action="{% url 'my_blog:new_topic_info' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add new topic info.</button>
</form>

{% endblock content %}

my_blog_app/templates/my_blog_app/topic_info.html
{% extends 'my_blog_app/base.html' %}

{% block content %}

    <h1><a href="{% url 'my_blog:new_topic_info' topic.id %}">Add new topic info.</a></h1>

    <h1>Information about topic {{ topic }}</h1>

    <ul>
        {% for info in topic_infos %}
            <li>{{ info.name }}</li>
            <li>{{ info.text }}</li>
        <br>
        {% empty %}
            <li>No topics available yet!</li>
        {% endfor %}
    </ul>

{% endblock content %}

my_blog_app/templates/my_blog_app/topics.html
{% extends 'my_blog_app/base.html' %}

{% block content %}


    <h1>All available topics</h1>

    <ul>
        {% for topic in all_topics %}
            <li><a href="{% url 'my_blog:topic_info' topic.id %}">{{ topic }}</a></li>
        <br>
        {% empty %}
            <li>No topics available yet!</li>
        {% endfor %}
    </ul>


{% endblock content %}